# Generated by Django 3.0 on 2021-05-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210430_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('mi', 'mi'), ('oppo', 'oppo'), ('vivo', 'vivo'), ('apple', 'apple'), ('girlwatch', 'girlwatch'), ('boywatch', 'boywatch')], max_length=100),
        ),
    ]
